version: '3.3'

services:
  to-do-api:
    image: postgres:13
    environment:
      - POSTGRES_DB=dental-clinic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
